### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by 1634145594** [acoursey3/freeway-anomaly-detection#1]
First of all, thank you to this blogger. Recently, I have been running your code files and found that some files are missing, such as the saved. psh extension file, and some code has some errors that cannot be fully executed.

**Comment by acoursey3** [comment]
I appreciate your interest in our repository! Thank you for bringing this issue to our attention. I will spend some time this week 

1. reinstalling the repository and ensuring all code can be executed and 
2. documenting the code further to facilitate ease of use.

I will update this issue when this is resolved.

**Comment by acoursey3** [comment]
**Update**: I have cleaned up the codebase significantly, including removing notebook files that were not included in the paper's experiments. I also installed the repository from scratch and reran all files to ensure they worked. Please let me know if you have any other issues or questions!

Happy anomaly detecting.
